# ----------------------------------------------------------------------------
# GitHub Actions workflow that causes rebuild of all CGE repos
# that rely on CGE Docker images.
# This allows to test that the new CGE (Docker, GitHub code) is compatible
# with all CGE projects.
# ----------------------------------------------------------------------------

name: After Build

# Called by other xxx.yml
on: [workflow_call]

defaults:
  run:
    shell: bash

jobs:
  dispatch-rebuild:
    name: Dispatch Rebuild To Other Repos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Make https://github.com/castle-engine/castle-engine-docker
    # rebuild Docker image with the latest CGE snapshot.
    #
    # See repository_dispatch docs:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
    # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
    - name: Dispatch updating Docker cge-unstable
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_DISPATCH_AFTER_UPDATE }}
      run: |
        gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/castle-engine/castle-model-viewer/dispatches \
          -f "event_type=cge-docker-unstable-changed"  \
          -F "client_payload[cge_docker_commit_sha]=${{ github.sha }}"
        gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/castle-engine/castle-model-viewer-mobile/dispatches \
          -f "event_type=cge-docker-unstable-changed"  \
          -F "client_payload[cge_docker_commit_sha]=${{ github.sha }}"
        gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/castle-engine/cge-www/dispatches \
          -f "event_type=cge-docker-unstable-changed"  \
          -F "client_payload[cge_docker_commit_sha]=${{ github.sha }}"
