# ----------------------------------------------------------------------------
# GitHub Actions workflow that causes rebuild of all CGE repos
# that rely on CGE Docker images.
# This allows to test that the new CGE (Docker, GitHub code) is compatible
# with all CGE projects.
# ----------------------------------------------------------------------------

name: After Build

# Called by other xxx.yml
on:
  workflow_call:
    secrets:
      GH_TOKEN_DISPATCH_AFTER_UPDATE:
        description: 'GitHub token to allow dispatching workflows to all other CGE repos'
        required: true

defaults:
  run:
    shell: bash

jobs:
  dispatch-rebuild:
    name: Dispatch Rebuild To Other Repos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Make https://github.com/castle-engine/castle-engine-docker
    # rebuild Docker image with the latest CGE snapshot.
    - name: Dispatch updating Docker cge-unstable
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_DISPATCH_AFTER_UPDATE }}
      run: |
        ./dispatch_cge_docker_unstable_changed.sh "${{ github.sha }}" castle-engine/castle-model-viewer
        ./dispatch_cge_docker_unstable_changed.sh "${{ github.sha }}" castle-engine/castle-model-viewer-mobile
        ./dispatch_cge_docker_unstable_changed.sh "${{ github.sha }}" castle-engine/cge-www
