# ----------------------------------------------------------------------------
# GitHub Actions workflow that updates all Docker images of Castle Game Engine:
#
# - cge-none (prerequisites, like FPC (stable versuib),
#   Android SDK/NDK, texture tools...),
# - cge-none-fpxXXX (same as cge-none but with alternative FPC version,
#   see https://hub.docker.com/r/kambi/castle-engine-cloud-builds-tools/ )
# - cge-stable, cge-unstable
#
# See https://castle-engine.io/docker for more about this Docker image.
# ----------------------------------------------------------------------------

name: Update All CGE Docker Images

on:
  # Manually trigger the workflow.
  # This is seldom necessary (and takes a long time).
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Split build.sh into 3 smaller jobs,
    # to avoid "disk size exceeded" errors from GH actions on GH-hosted runners.

    - name: cge-none, cge-none-fpxXXX
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_GITHUB_USER: ${{ secrets.DOCKER_GITHUB_USER }}
        DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        IFS=$'\n\t'
        source build-common.sh
        do_everything_for_image_none

    - name: cge-stable
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_GITHUB_USER: ${{ secrets.DOCKER_GITHUB_USER }}
        DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        IFS=$'\n\t'
        source build-common.sh
        do_everything_for_image_stable

    - name: cge-unstable
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_GITHUB_USER: ${{ secrets.DOCKER_GITHUB_USER }}
        DOCKER_GITHUB_TOKEN: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        IFS=$'\n\t'
        source build-common.sh
        do_everything_for_image_unstable
